version: "3"
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "3443:443"
    environment:
      STAGE: local
      # DOMAINS: "localhost -> http://host.docker.internal:3000"
      DOMAINS: "192.168.1.2 -> http://host.docker.internal:3000"
